### ISSUE TITLE
multer will not upload the images

### ISSUE THREAD

**Issue by zcarey90** [zcarey90/MTX-Bank-Notes#1]
multer wont upload the images

**Comment by jddalessandro** [comment]
post your error and I'll take a look. I don't use multer but the error might be more general

**Comment by zcarey90** [comment]
![Screen Shot 2020-12-18 at 9 54 15 AM](https://user-images.githubusercontent.com/49701090/102635428-4ad2fe80-4121-11eb-9c30-e57e62b6df4d.png)

**Comment by jddalessandro** [comment]
what file is that in? I don't see those lines of code in the repo

**Comment by jddalessandro** [comment]
it looks like you're not using the proper syntax to interpolate a string

the param passed into `readFile` should use backticks as a wrapper instead of double quotes

**Comment by zcarey90** [comment]
it changes it over from ' to " when I save it

**Comment by zcarey90** [comment]
sorry when I use ` I still get the same error

**Comment by jddalessandro** [comment]
is the code in the repo your latest?

**Comment by zcarey90** [comment]
yeah I just pushed it

**Comment by zcarey90** [comment]
I haven't messed with multer that much either so I am going to npm install multer and see what that does.

**Comment by zcarey90** [comment]
![Screen Shot 2020-12-18 at 11 30 27 AM 1](https://user-images.githubusercontent.com/49701090/102637771-86bb9300-4124-11eb-8a71-66f2fe5c49da.png)
 thats the newest error that i get

**Comment by jddalessandro** [comment]
Solved in PR #2 

this should be resolved when you merge and pull. I'm gonna close this issue
